name: Deploy to 000webhost
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: files.000webhost.com
        username: buildecsite
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        local-dir: ./